site_name: My Docs

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.action.edit
    - content.tabs.link

nav:
  - Home: index.md
  - Mermaid examples:
    - Network graph: mermaid-examples/network-graph.md
    #- Network diagram: mermaid-examples/network-diagram.md
    - Sequence diagram: mermaid-examples/sequence-diagram.md

markdown_extensions:
  - toc
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search:
      lang: en
  - mermaid2
